'use strict';

/**
 * @ngdoc service
 * @name bprApp.constants
 * @description
 * # constants
 * Constant in the bprApp.
 */
angular.module('bprApp')
  .constant('API_CONFIG', (function() {
    var PROTOCOL = '//';
    var IP = 'api.dev.witbooker.com';
    var PORT = '';
    var PATH = '';
/*

    var PROTOCOL = 'http://';
    var IP = 'localhost';
    var PORT = '8080';
    var PATH = 'WitBookerAPI-war/webresources';
*/
/*
    var IP = 'localhost';
    var PORT = '8080';
    var PATH = 'WitBookerAPI-war/webresources';
    var BASE_URL= PROTOCOL+IP+":"+PORT+"/"+PATH;
*/
    var BASE_URL= PROTOCOL+IP+":"+PORT+"/"+PATH;
    return {
      BASE_URL: BASE_URL,
      BOOKING_PRICE_RULE_URL: BASE_URL+"/"+"bookingPriceRule"
    }
  })())
  .constant('DEFAULT_DATE_PICKER_SETTINGS',{
    regional: 'es',
    dateFormat: "dd-mm-yy"
  })
  .constant('DYNAMIC_PRICING_TEMPLATE_LOCATION',"views/")
  .constant('SUPPORTED_LANGUAGES',["en","es"])
  .constant('DEFAULT_LANGUAGE',"es")
  .constant('DATE_FORMAT',"dd-mm-yy")
  .constant('DATE_TIME_FORMAT',"YYYY-MM-DDTHH:mm:ss.SSSZ")
  .constant('TIMEZONE_OFFSET',"Z")
  .constant('DATE_TIME_FORMAT_NO_OFFSET',"YYYY-MM-DDTHH:mm:ss.SSS")
  .constant('TIME_FORMAT',"HH:mm:ss.SSSZ")
  .constant('TIME_FORMAT_NO_OFFSET',"HH:mm:ss.SSS")
  .constant('WEEKDAYS',['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'])
  .constant('CONDITION_CLASS',{
    COUNTRY_OF_ORIGIN:"CountryOfOriginCondition",
    DATE_TIME_RANGE:"DatetimeRangeCondition",
    HOUR_RANGE:"HourRangeCondition",
    WEEK_DAY:"WeekDayCondition",
    CODE:"CodeCondition",
    TICKER:"TickerCondition"
  })
  .constant('CONDITION_TYPE',{
    INCLUDE:"INCLUDE",
    EXCLUDE:"EXCLUDE",
    ALL:"ALL",
    STAY:"STAY",
    EXACT:"EXACT",
    CONTRACT:"CONTRACT"
  })
  .constant('TIMEZONES',	[
    {"offset":"-12:00","value":"Etc/GMT+12","text":"(GMT -12:00) Etc/GMT+12"},
    {"offset":"-11:00","value":"Pacific/Samoa","text":"(GMT -11:00) Pacific/Samoa"},
    {"offset":"-11:00","value":"Pacific/Pago_Pago","text":"(GMT -11:00) Pacific/Pago_Pago"},
    {"offset":"-11:00","value":"Pacific/Niue","text":"(GMT -11:00) Pacific/Niue"},
    {"offset":"-11:00","value":"Pacific/Midway","text":"(GMT -11:00) Pacific/Midway"},
    {"offset":"-11:00","value":"US/Samoa","text":"(GMT -11:00) US/Samoa"},
    {"offset":"-11:00","value":"Etc/GMT+11","text":"(GMT -11:00) Etc/GMT+11"},
    {"offset":"-10:00","value":"Pacific/Johnston","text":"(GMT -10:00) Pacific/Johnston"},
    {"offset":"-10:00","value":"America/Atka","text":"(GMT -10:00) America/Atka"},
    {"offset":"-10:00","value":"US/Aleutian","text":"(GMT -10:00) US/Aleutian"},
    {"offset":"-10:00","value":"Pacific/Honolulu","text":"(GMT -10:00) Pacific/Honolulu"},
    {"offset":"-10:00","value":"US/Hawaii","text":"(GMT -10:00) US/Hawaii"},
    {"offset":"-10:00","value":"America/Adak","text":"(GMT -10:00) America/Adak"},
    {"offset":"-10:00","value":"Pacific/Tahiti","text":"(GMT -10:00) Pacific/Tahiti"},
    {"offset":"-10:00","value":"Etc/GMT+10","text":"(GMT -10:00) Etc/GMT+10"},
    {"offset":"-10:00","value":"HST","text":"(GMT -10:00) HST"},
    {"offset":"-10:00","value":"Pacific/Rarotonga","text":"(GMT -10:00) Pacific/Rarotonga"},
    {"offset":"-09:30","value":"Pacific/Marquesas","text":"(GMT -09:30) Pacific/Marquesas"},
    {"offset":"-09:00","value":"Pacific/Gambier","text":"(GMT -09:00) Pacific/Gambier"},
    {"offset":"-09:00","value":"America/Anchorage","text":"(GMT -09:00) America/Anchorage"},
    {"offset":"-09:00","value":"America/Nome","text":"(GMT -09:00) America/Nome"},
    {"offset":"-09:00","value":"US/Alaska","text":"(GMT -09:00) US/Alaska"},
    {"offset":"-09:00","value":"Etc/GMT+9","text":"(GMT -09:00) Etc/GMT+9"},
    {"offset":"-09:00","value":"America/Juneau","text":"(GMT -09:00) America/Juneau"},
    {"offset":"-09:00","value":"America/Yakutat","text":"(GMT -09:00) America/Yakutat"},
    {"offset":"-09:00","value":"America/Sitka","text":"(GMT -09:00) America/Sitka"},
    {"offset":"-08:00","value":"Mexico/BajaNorte","text":"(GMT -08:00) Mexico/BajaNorte"},
    {"offset":"-08:00","value":"America/Dawson","text":"(GMT -08:00) America/Dawson"},
    {"offset":"-08:00","value":"Pacific/Pitcairn","text":"(GMT -08:00) Pacific/Pitcairn"},
    {"offset":"-08:00","value":"America/Metlakatla","text":"(GMT -08:00) America/Metlakatla"},
    {"offset":"-08:00","value":"Etc/GMT+8","text":"(GMT -08:00) Etc/GMT+8"},
    {"offset":"-08:00","value":"PST8PDT","text":"(GMT -08:00) PST8PDT"},
    {"offset":"-08:00","value":"America/Santa_Isabel","text":"(GMT -08:00) America/Santa_Isabel"},
    {"offset":"-08:00","value":"Canada/Pacific","text":"(GMT -08:00) Canada/Pacific"},
    {"offset":"-08:00","value":"US/Pacific","text":"(GMT -08:00) US/Pacific"},
    {"offset":"-08:00","value":"US/Pacific-New","text":"(GMT -08:00) US/Pacific-New"},
    {"offset":"-08:00","value":"Canada/Yukon","text":"(GMT -08:00) Canada/Yukon"},
    {"offset":"-08:00","value":"America/Whitehorse","text":"(GMT -08:00) America/Whitehorse"},
    {"offset":"-08:00","value":"America/Vancouver","text":"(GMT -08:00) America/Vancouver"},
    {"offset":"-08:00","value":"America/Ensenada","text":"(GMT -08:00) America/Ensenada"},
    {"offset":"-08:00","value":"America/Tijuana","text":"(GMT -08:00) America/Tijuana"},
    {"offset":"-08:00","value":"America/Los_Angeles","text":"(GMT -08:00) America/Los_Angeles"},
    {"offset":"-07:00","value":"Etc/GMT+7","text":"(GMT -07:00) Etc/GMT+7"},
    {"offset":"-07:00","value":"America/Hermosillo","text":"(GMT -07:00) America/Hermosillo"},
    {"offset":"-07:00","value":"America/Yellowknife","text":"(GMT -07:00) America/Yellowknife"},
    {"offset":"-07:00","value":"America/Phoenix","text":"(GMT -07:00) America/Phoenix"},
    {"offset":"-07:00","value":"Navajo","text":"(GMT -07:00) Navajo"},
    {"offset":"-07:00","value":"Canada/Mountain","text":"(GMT -07:00) Canada/Mountain"},
    {"offset":"-07:00","value":"America/Boise","text":"(GMT -07:00) America/Boise"},
    {"offset":"-07:00","value":"America/Ojinaga","text":"(GMT -07:00) America/Ojinaga"},
    {"offset":"-07:00","value":"America/Cambridge_Bay","text":"(GMT -07:00) America/Cambridge_Bay"},
    {"offset":"-07:00","value":"Mexico/BajaSur","text":"(GMT -07:00) Mexico/BajaSur"},
    {"offset":"-07:00","value":"America/Shiprock","text":"(GMT -07:00) America/Shiprock"},
    {"offset":"-07:00","value":"US/Arizona","text":"(GMT -07:00) US/Arizona"},
    {"offset":"-07:00","value":"MST7MDT","text":"(GMT -07:00) MST7MDT"},
    {"offset":"-07:00","value":"MST","text":"(GMT -07:00) MST"},
    {"offset":"-07:00","value":"US/Mountain","text":"(GMT -07:00) US/Mountain"},
    {"offset":"-07:00","value":"America/Chihuahua","text":"(GMT -07:00) America/Chihuahua"},
    {"offset":"-07:00","value":"America/Edmonton","text":"(GMT -07:00) America/Edmonton"},
    {"offset":"-07:00","value":"America/Creston","text":"(GMT -07:00) America/Creston"},
    {"offset":"-07:00","value":"America/Inuvik","text":"(GMT -07:00) America/Inuvik"},
    {"offset":"-07:00","value":"America/Mazatlan","text":"(GMT -07:00) America/Mazatlan"},
    {"offset":"-07:00","value":"America/Dawson_Creek","text":"(GMT -07:00) America/Dawson_Creek"},
    {"offset":"-07:00","value":"America/Denver","text":"(GMT -07:00) America/Denver"},
    {"offset":"-06:00","value":"Canada/Saskatchewan","text":"(GMT -06:00) Canada/Saskatchewan"},
    {"offset":"-06:00","value":"America/Tegucigalpa","text":"(GMT -06:00) America/Tegucigalpa"},
    {"offset":"-06:00","value":"America/El_Salvador","text":"(GMT -06:00) America/El_Salvador"},
    {"offset":"-06:00","value":"America/Chicago","text":"(GMT -06:00) America/Chicago"},
    {"offset":"-06:00","value":"America/Swift_Current","text":"(GMT -06:00) America/Swift_Current"},
    {"offset":"-06:00","value":"America/Winnipeg","text":"(GMT -06:00) America/Winnipeg"},
    {"offset":"-06:00","value":"America/Cancun","text":"(GMT -06:00) America/Cancun"},
    {"offset":"-06:00","value":"America/Belize","text":"(GMT -06:00) America/Belize"},
    {"offset":"-06:00","value":"America/Resolute","text":"(GMT -06:00) America/Resolute"},
    {"offset":"-06:00","value":"America/Regina","text":"(GMT -06:00) America/Regina"},
    {"offset":"-06:00","value":"America/Guatemala","text":"(GMT -06:00) America/Guatemala"},
    {"offset":"-06:00","value":"America/Rankin_Inlet","text":"(GMT -06:00) America/Rankin_Inlet"},
    {"offset":"-06:00","value":"America/Rainy_River","text":"(GMT -06:00) America/Rainy_River"},
    {"offset":"-06:00","value":"America/Bahia_Banderas","text":"(GMT -06:00) America/Bahia_Banderas"},
    {"offset":"-06:00","value":"America/Indiana/Knox","text":"(GMT -06:00) America/Indiana/Knox"},
    {"offset":"-06:00","value":"America/Indiana/Tell_City","text":"(GMT -06:00) America/Indiana/Tell_City"},
    {"offset":"-06:00","value":"Etc/GMT+6","text":"(GMT -06:00) Etc/GMT+6"},
    {"offset":"-06:00","value":"America/Costa_Rica","text":"(GMT -06:00) America/Costa_Rica"},
    {"offset":"-06:00","value":"Canada/East-Saskatchewan","text":"(GMT -06:00) Canada/East-Saskatchewan"},
    {"offset":"-06:00","value":"America/Knox_IN","text":"(GMT -06:00) America/Knox_IN"},
    {"offset":"-06:00","value":"Canada/Central","text":"(GMT -06:00) Canada/Central"},
    {"offset":"-06:00","value":"CST6CDT","text":"(GMT -06:00) CST6CDT"},
    {"offset":"-06:00","value":"America/Managua","text":"(GMT -06:00) America/Managua"},
    {"offset":"-06:00","value":"Mexico/General","text":"(GMT -06:00) Mexico/General"},
    {"offset":"-06:00","value":"America/North_Dakota/New_Salem","text":"(GMT -06:00) America/North_Dakota/New_Salem"},
    {"offset":"-06:00","value":"America/North_Dakota/Center","text":"(GMT -06:00) America/North_Dakota/Center"},
    {"offset":"-06:00","value":"America/Matamoros","text":"(GMT -06:00) America/Matamoros"},
    {"offset":"-06:00","value":"Pacific/Galapagos","text":"(GMT -06:00) Pacific/Galapagos"},
    {"offset":"-06:00","value":"America/North_Dakota/Beulah","text":"(GMT -06:00) America/North_Dakota/Beulah"},
    {"offset":"-06:00","value":"America/Menominee","text":"(GMT -06:00) America/Menominee"},
    {"offset":"-06:00","value":"America/Merida","text":"(GMT -06:00) America/Merida"},
    {"offset":"-06:00","value":"US/Central","text":"(GMT -06:00) US/Central"},
    {"offset":"-06:00","value":"America/Mexico_City","text":"(GMT -06:00) America/Mexico_City"},
    {"offset":"-06:00","value":"US/Indiana-Starke","text":"(GMT -06:00) US/Indiana-Starke"},
    {"offset":"-06:00","value":"America/Monterrey","text":"(GMT -06:00) America/Monterrey"},
    {"offset":"-05:00","value":"America/Toronto","text":"(GMT -05:00) America/Toronto"},
    {"offset":"-05:00","value":"Cuba","text":"(GMT -05:00) Cuba"},
    {"offset":"-05:00","value":"America/Havana","text":"(GMT -05:00) America/Havana"},
    {"offset":"-05:00","value":"EST","text":"(GMT -05:00) EST"},
    {"offset":"-05:00","value":"America/Indiana/Indianapolis","text":"(GMT -05:00) America/Indiana/Indianapolis"},
    {"offset":"-05:00","value":"EST5EDT","text":"(GMT -05:00) EST5EDT"},
    {"offset":"-05:00","value":"America/Indiana/Marengo","text":"(GMT -05:00) America/Indiana/Marengo"},
    {"offset":"-05:00","value":"America/Indiana/Petersburg","text":"(GMT -05:00) America/Indiana/Petersburg"},
    {"offset":"-05:00","value":"America/Thunder_Bay","text":"(GMT -05:00) America/Thunder_Bay"},
    {"offset":"-05:00","value":"America/Indiana/Vevay","text":"(GMT -05:00) America/Indiana/Vevay"},
    {"offset":"-05:00","value":"America/Indiana/Vincennes","text":"(GMT -05:00) America/Indiana/Vincennes"},
    {"offset":"-05:00","value":"America/Indiana/Winamac","text":"(GMT -05:00) America/Indiana/Winamac"},
    {"offset":"-05:00","value":"America/Indianapolis","text":"(GMT -05:00) America/Indianapolis"},
    {"offset":"-05:00","value":"Jamaica","text":"(GMT -05:00) Jamaica"},
    {"offset":"-05:00","value":"America/Iqaluit","text":"(GMT -05:00) America/Iqaluit"},
    {"offset":"-05:00","value":"America/Jamaica","text":"(GMT -05:00) America/Jamaica"},
    {"offset":"-05:00","value":"America/Porto_Acre","text":"(GMT -05:00) America/Porto_Acre"},
    {"offset":"-05:00","value":"America/Bogota","text":"(GMT -05:00) America/Bogota"},
    {"offset":"-05:00","value":"America/Kentucky/Louisville","text":"(GMT -05:00) America/Kentucky/Louisville"},
    {"offset":"-05:00","value":"America/Kentucky/Monticello","text":"(GMT -05:00) America/Kentucky/Monticello"},
    {"offset":"-05:00","value":"America/Detroit","text":"(GMT -05:00) America/Detroit"},
    {"offset":"-05:00","value":"America/Port-au-Prince","text":"(GMT -05:00) America/Port-au-Prince"},
    {"offset":"-05:00","value":"US/Michigan","text":"(GMT -05:00) US/Michigan"},
    {"offset":"-05:00","value":"America/Lima","text":"(GMT -05:00) America/Lima"},
    {"offset":"-05:00","value":"Canada/Eastern","text":"(GMT -05:00) Canada/Eastern"},
    {"offset":"-05:00","value":"America/Louisville","text":"(GMT -05:00) America/Louisville"},
    {"offset":"-05:00","value":"America/Pangnirtung","text":"(GMT -05:00) America/Pangnirtung"},
    {"offset":"-05:00","value":"America/Panama","text":"(GMT -05:00) America/Panama"},
    {"offset":"-05:00","value":"America/Eirunepe","text":"(GMT -05:00) America/Eirunepe"},
    {"offset":"-05:00","value":"Etc/GMT+5","text":"(GMT -05:00) Etc/GMT+5"},
    {"offset":"-05:00","value":"US/Eastern","text":"(GMT -05:00) US/Eastern"},
    {"offset":"-05:00","value":"America/Fort_Wayne","text":"(GMT -05:00) America/Fort_Wayne"},
    {"offset":"-05:00","value":"America/Atikokan","text":"(GMT -05:00) America/Atikokan"},
    {"offset":"-05:00","value":"US/East-Indiana","text":"(GMT -05:00) US/East-Indiana"},
    {"offset":"-05:00","value":"Brazil/Acre","text":"(GMT -05:00) Brazil/Acre"},
    {"offset":"-05:00","value":"America/Cayman","text":"(GMT -05:00) America/Cayman"},
    {"offset":"-05:00","value":"America/Rio_Branco","text":"(GMT -05:00) America/Rio_Branco"},
    {"offset":"-05:00","value":"Pacific/Easter","text":"(GMT -05:00) Pacific/Easter"},
    {"offset":"-05:00","value":"Chile/EasterIsland","text":"(GMT -05:00) Chile/EasterIsland"},
    {"offset":"-05:00","value":"America/Coral_Harbour","text":"(GMT -05:00) America/Coral_Harbour"},
    {"offset":"-05:00","value":"America/Nipigon","text":"(GMT -05:00) America/Nipigon"},
    {"offset":"-05:00","value":"America/Guayaquil","text":"(GMT -05:00) America/Guayaquil"},
    {"offset":"-05:00","value":"America/New_York","text":"(GMT -05:00) America/New_York"},
    {"offset":"-05:00","value":"America/Montreal","text":"(GMT -05:00) America/Montreal"},
    {"offset":"-05:00","value":"America/Nassau","text":"(GMT -05:00) America/Nassau"},
    {"offset":"-04:30","value":"America/Caracas","text":"(GMT -04:30) America/Caracas"},
    {"offset":"-04:00","value":"America/Tortola","text":"(GMT -04:00) America/Tortola"},
    {"offset":"-04:00","value":"America/Moncton","text":"(GMT -04:00) America/Moncton"},
    {"offset":"-04:00","value":"America/Anguilla","text":"(GMT -04:00) America/Anguilla"},
    {"offset":"-04:00","value":"Brazil/West","text":"(GMT -04:00) Brazil/West"},
    {"offset":"-04:00","value":"America/Antigua","text":"(GMT -04:00) America/Antigua"},
    {"offset":"-04:00","value":"America/Martinique","text":"(GMT -04:00) America/Martinique"},
    {"offset":"-04:00","value":"America/Marigot","text":"(GMT -04:00) America/Marigot"},
    {"offset":"-04:00","value":"America/Manaus","text":"(GMT -04:00) America/Manaus"},
    {"offset":"-04:00","value":"Canada/Atlantic","text":"(GMT -04:00) Canada/Atlantic"},
    {"offset":"-04:00","value":"America/Lower_Princes","text":"(GMT -04:00) America/Lower_Princes"},
    {"offset":"-04:00","value":"Etc/GMT+4","text":"(GMT -04:00) Etc/GMT+4"},
    {"offset":"-04:00","value":"America/La_Paz","text":"(GMT -04:00) America/La_Paz"},
    {"offset":"-04:00","value":"America/Kralendijk","text":"(GMT -04:00) America/Kralendijk"},
    {"offset":"-04:00","value":"America/Port_of_Spain","text":"(GMT -04:00) America/Port_of_Spain"},
    {"offset":"-04:00","value":"America/Aruba","text":"(GMT -04:00) America/Aruba"},
    {"offset":"-04:00","value":"America/Porto_Velho","text":"(GMT -04:00) America/Porto_Velho"},
    {"offset":"-04:00","value":"America/Puerto_Rico","text":"(GMT -04:00) America/Puerto_Rico"},
    {"offset":"-04:00","value":"America/Halifax","text":"(GMT -04:00) America/Halifax"},
    {"offset":"-04:00","value":"America/Guyana","text":"(GMT -04:00) America/Guyana"},
    {"offset":"-04:00","value":"America/Barbados","text":"(GMT -04:00) America/Barbados"},
    {"offset":"-04:00","value":"America/Guadeloupe","text":"(GMT -04:00) America/Guadeloupe"},
    {"offset":"-04:00","value":"America/Grenada","text":"(GMT -04:00) America/Grenada"},
    {"offset":"-04:00","value":"America/Grand_Turk","text":"(GMT -04:00) America/Grand_Turk"},
    {"offset":"-04:00","value":"America/Blanc-Sablon","text":"(GMT -04:00) America/Blanc-Sablon"},
    {"offset":"-04:00","value":"America/Goose_Bay","text":"(GMT -04:00) America/Goose_Bay"},
    {"offset":"-04:00","value":"America/Boa_Vista","text":"(GMT -04:00) America/Boa_Vista"},
    {"offset":"-04:00","value":"America/Montserrat","text":"(GMT -04:00) America/Montserrat"},
    {"offset":"-04:00","value":"America/Santo_Domingo","text":"(GMT -04:00) America/Santo_Domingo"},
    {"offset":"-04:00","value":"America/Virgin","text":"(GMT -04:00) America/Virgin"},
    {"offset":"-04:00","value":"America/Curacao","text":"(GMT -04:00) America/Curacao"},
    {"offset":"-04:00","value":"America/Glace_Bay","text":"(GMT -04:00) America/Glace_Bay"},
    {"offset":"-04:00","value":"America/St_Barthelemy","text":"(GMT -04:00) America/St_Barthelemy"},
    {"offset":"-04:00","value":"America/Thule","text":"(GMT -04:00) America/Thule"},
    {"offset":"-04:00","value":"America/St_Kitts","text":"(GMT -04:00) America/St_Kitts"},
    {"offset":"-04:00","value":"America/St_Lucia","text":"(GMT -04:00) America/St_Lucia"},
    {"offset":"-04:00","value":"America/St_Thomas","text":"(GMT -04:00) America/St_Thomas"},
    {"offset":"-04:00","value":"America/St_Vincent","text":"(GMT -04:00) America/St_Vincent"},
    {"offset":"-04:00","value":"America/Dominica","text":"(GMT -04:00) America/Dominica"},
    {"offset":"-04:00","value":"Atlantic/Bermuda","text":"(GMT -04:00) Atlantic/Bermuda"},
    {"offset":"-03:30","value":"America/St_Johns","text":"(GMT -03:30) America/St_Johns"},
    {"offset":"-03:30","value":"Canada/Newfoundland","text":"(GMT -03:30) Canada/Newfoundland"},
    {"offset":"-03:00","value":"America/Cuiaba","text":"(GMT -03:00) America/Cuiaba"},
    {"offset":"-03:00","value":"America/Cordoba","text":"(GMT -03:00) America/Cordoba"},
    {"offset":"-03:00","value":"Atlantic/Stanley","text":"(GMT -03:00) Atlantic/Stanley"},
    {"offset":"-03:00","value":"America/Cayenne","text":"(GMT -03:00) America/Cayenne"},
    {"offset":"-03:00","value":"America/Miquelon","text":"(GMT -03:00) America/Miquelon"},
    {"offset":"-03:00","value":"America/Catamarca","text":"(GMT -03:00) America/Catamarca"},
    {"offset":"-03:00","value":"America/Santiago","text":"(GMT -03:00) America/Santiago"},
    {"offset":"-03:00","value":"America/Campo_Grande","text":"(GMT -03:00) America/Campo_Grande"},
    {"offset":"-03:00","value":"America/Buenos_Aires","text":"(GMT -03:00) America/Buenos_Aires"},
    {"offset":"-03:00","value":"America/Santarem","text":"(GMT -03:00) America/Santarem"},
    {"offset":"-03:00","value":"America/Rosario","text":"(GMT -03:00) America/Rosario"},
    {"offset":"-03:00","value":"Antarctica/Palmer","text":"(GMT -03:00) Antarctica/Palmer"},
    {"offset":"-03:00","value":"Antarctica/Rothera","text":"(GMT -03:00) Antarctica/Rothera"},
    {"offset":"-03:00","value":"America/Belem","text":"(GMT -03:00) America/Belem"},
    {"offset":"-03:00","value":"America/Recife","text":"(GMT -03:00) America/Recife"},
    {"offset":"-03:00","value":"America/Bahia","text":"(GMT -03:00) America/Bahia"},
    {"offset":"-03:00","value":"America/Asuncion","text":"(GMT -03:00) America/Asuncion"},
    {"offset":"-03:00","value":"America/Jujuy","text":"(GMT -03:00) America/Jujuy"},
    {"offset":"-03:00","value":"America/Paramaribo","text":"(GMT -03:00) America/Paramaribo"},
    {"offset":"-03:00","value":"Etc/GMT+3","text":"(GMT -03:00) Etc/GMT+3"},
    {"offset":"-03:00","value":"America/Mendoza","text":"(GMT -03:00) America/Mendoza"},
    {"offset":"-03:00","value":"America/Fortaleza","text":"(GMT -03:00) America/Fortaleza"},
    {"offset":"-03:00","value":"America/Argentina/Tucuman","text":"(GMT -03:00) America/Argentina/Tucuman"},
    {"offset":"-03:00","value":"America/Argentina/San_Luis","text":"(GMT -03:00) America/Argentina/San_Luis"},
    {"offset":"-03:00","value":"America/Argentina/San_Juan","text":"(GMT -03:00) America/Argentina/San_Juan"},
    {"offset":"-03:00","value":"America/Argentina/Salta","text":"(GMT -03:00) America/Argentina/Salta"},
    {"offset":"-03:00","value":"America/Argentina/Rio_Gallegos","text":"(GMT -03:00) America/Argentina/Rio_Gallegos"},
    {"offset":"-03:00","value":"America/Argentina/Mendoza","text":"(GMT -03:00) America/Argentina/Mendoza"},
    {"offset":"-03:00","value":"Chile/Continental","text":"(GMT -03:00) Chile/Continental"},
    {"offset":"-03:00","value":"America/Argentina/La_Rioja","text":"(GMT -03:00) America/Argentina/La_Rioja"},
    {"offset":"-03:00","value":"America/Argentina/Jujuy","text":"(GMT -03:00) America/Argentina/Jujuy"},
    {"offset":"-03:00","value":"America/Argentina/Cordoba","text":"(GMT -03:00) America/Argentina/Cordoba"},
    {"offset":"-03:00","value":"America/Godthab","text":"(GMT -03:00) America/Godthab"},
    {"offset":"-03:00","value":"America/Argentina/ComodRivadavia","text":"(GMT -03:00) America/Argentina/ComodRivadavia"},
    {"offset":"-03:00","value":"America/Argentina/Catamarca","text":"(GMT -03:00) America/Argentina/Catamarca"},
    {"offset":"-03:00","value":"America/Argentina/Buenos_Aires","text":"(GMT -03:00) America/Argentina/Buenos_Aires"},
    {"offset":"-03:00","value":"America/Araguaina","text":"(GMT -03:00) America/Araguaina"},
    {"offset":"-03:00","value":"America/Maceio","text":"(GMT -03:00) America/Maceio"},
    {"offset":"-03:00","value":"America/Argentina/Ushuaia","text":"(GMT -03:00) America/Argentina/Ushuaia"},
    {"offset":"-02:00","value":"Etc/GMT+2","text":"(GMT -02:00) Etc/GMT+2"},
    {"offset":"-02:00","value":"America/Noronha","text":"(GMT -02:00) America/Noronha"},
    {"offset":"-02:00","value":"Brazil/East","text":"(GMT -02:00) Brazil/East"},
    {"offset":"-02:00","value":"Brazil/DeNoronha","text":"(GMT -02:00) Brazil/DeNoronha"},
    {"offset":"-02:00","value":"America/Sao_Paulo","text":"(GMT -02:00) America/Sao_Paulo"},
    {"offset":"-02:00","value":"America/Montevideo","text":"(GMT -02:00) America/Montevideo"},
    {"offset":"-02:00","value":"Atlantic/South_Georgia","text":"(GMT -02:00) Atlantic/South_Georgia"},
    {"offset":"-01:00","value":"America/Scoresbysund","text":"(GMT -01:00) America/Scoresbysund"},
    {"offset":"-01:00","value":"Etc/GMT+1","text":"(GMT -01:00) Etc/GMT+1"},
    {"offset":"-01:00","value":"Atlantic/Cape_Verde","text":"(GMT -01:00) Atlantic/Cape_Verde"},
    {"offset":"-01:00","value":"Atlantic/Azores","text":"(GMT -01:00) Atlantic/Azores"},
    {"offset":"+00:00","value":"Africa/Abidjan","text":"(GMT +00:00) Africa/Abidjan"},
    {"offset":"+00:00","value":"Europe/Belfast","text":"(GMT +00:00) Europe/Belfast"},
    {"offset":"+00:00","value":"Etc/Zulu","text":"(GMT +00:00) Etc/Zulu"},
    {"offset":"+00:00","value":"Etc/Universal","text":"(GMT +00:00) Etc/Universal"},
    {"offset":"+00:00","value":"Etc/UTC","text":"(GMT +00:00) Etc/UTC"},
    {"offset":"+00:00","value":"Etc/UCT","text":"(GMT +00:00) Etc/UCT"},
    {"offset":"+00:00","value":"Etc/Greenwich","text":"(GMT +00:00) Etc/Greenwich"},
    {"offset":"+00:00","value":"Etc/GMT0","text":"(GMT +00:00) Etc/GMT0"},
    {"offset":"+00:00","value":"Etc/GMT-0","text":"(GMT +00:00) Etc/GMT-0"},
    {"offset":"+00:00","value":"Africa/El_Aaiun","text":"(GMT +00:00) Africa/El_Aaiun"},
    {"offset":"+00:00","value":"Africa/Freetown","text":"(GMT +00:00) Africa/Freetown"},
    {"offset":"+00:00","value":"UTC","text":"(GMT +00:00) UTC"},
    {"offset":"+00:00","value":"Zulu","text":"(GMT +00:00) Zulu"},
    {"offset":"+00:00","value":"Africa/Bamako","text":"(GMT +00:00) Africa/Bamako"},
    {"offset":"+00:00","value":"America/Danmarkshavn","text":"(GMT +00:00) America/Danmarkshavn"},
    {"offset":"+00:00","value":"UCT","text":"(GMT +00:00) UCT"},
    {"offset":"+00:00","value":"Africa/Monrovia","text":"(GMT +00:00) Africa/Monrovia"},
    {"offset":"+00:00","value":"Portugal","text":"(GMT +00:00) Portugal"},
    {"offset":"+00:00","value":"Africa/Casablanca","text":"(GMT +00:00) Africa/Casablanca"},
    {"offset":"+00:00","value":"WET","text":"(GMT +00:00) WET"},
    {"offset":"+00:00","value":"Africa/Nouakchott","text":"(GMT +00:00) Africa/Nouakchott"},
    {"offset":"+00:00","value":"Etc/GMT+0","text":"(GMT +00:00) Etc/GMT+0"},
    {"offset":"+00:00","value":"Etc/GMT","text":"(GMT +00:00) Etc/GMT"},
    {"offset":"+00:00","value":"Eire","text":"(GMT +00:00) Eire"},
    {"offset":"+00:00","value":"Africa/Ouagadougou","text":"(GMT +00:00) Africa/Ouagadougou"},
    {"offset":"+00:00","value":"Africa/Conakry","text":"(GMT +00:00) Africa/Conakry"},
    {"offset":"+00:00","value":"Africa/Sao_Tome","text":"(GMT +00:00) Africa/Sao_Tome"},
    {"offset":"+00:00","value":"Africa/Timbuktu","text":"(GMT +00:00) Africa/Timbuktu"},
    {"offset":"+00:00","value":"Africa/Dakar","text":"(GMT +00:00) Africa/Dakar"},
    {"offset":"+00:00","value":"Africa/Banjul","text":"(GMT +00:00) Africa/Banjul"},
    {"offset":"+00:00","value":"Iceland","text":"(GMT +00:00) Iceland"},
    {"offset":"+00:00","value":"Africa/Lome","text":"(GMT +00:00) Africa/Lome"},
    {"offset":"+00:00","value":"Greenwich","text":"(GMT +00:00) Greenwich"},
    {"offset":"+00:00","value":"GMT0","text":"(GMT +00:00) GMT0"},
    {"offset":"+00:00","value":"GMT-0","text":"(GMT +00:00) GMT-0"},
    {"offset":"+00:00","value":"Africa/Bissau","text":"(GMT +00:00) Africa/Bissau"},
    {"offset":"+00:00","value":"Universal","text":"(GMT +00:00) Universal"},
    {"offset":"+00:00","value":"GMT+0","text":"(GMT +00:00) GMT+0"},
    {"offset":"+00:00","value":"GMT","text":"(GMT +00:00) GMT"},
    {"offset":"+00:00","value":"Antarctica/Troll","text":"(GMT +00:00) Antarctica/Troll"},
    {"offset":"+00:00","value":"GB-Eire","text":"(GMT +00:00) GB-Eire"},
    {"offset":"+00:00","value":"GB","text":"(GMT +00:00) GB"},
    {"offset":"+00:00","value":"Europe/London","text":"(GMT +00:00) Europe/London"},
    {"offset":"+00:00","value":"Europe/Lisbon","text":"(GMT +00:00) Europe/Lisbon"},
    {"offset":"+00:00","value":"Atlantic/St_Helena","text":"(GMT +00:00) Atlantic/St_Helena"},
    {"offset":"+00:00","value":"Europe/Jersey","text":"(GMT +00:00) Europe/Jersey"},
    {"offset":"+00:00","value":"Atlantic/Reykjavik","text":"(GMT +00:00) Atlantic/Reykjavik"},
    {"offset":"+00:00","value":"Atlantic/Madeira","text":"(GMT +00:00) Atlantic/Madeira"},
    {"offset":"+00:00","value":"Atlantic/Faroe","text":"(GMT +00:00) Atlantic/Faroe"},
    {"offset":"+00:00","value":"Atlantic/Faeroe","text":"(GMT +00:00) Atlantic/Faeroe"},
    {"offset":"+00:00","value":"Europe/Isle_of_Man","text":"(GMT +00:00) Europe/Isle_of_Man"},
    {"offset":"+00:00","value":"Atlantic/Canary","text":"(GMT +00:00) Atlantic/Canary"},
    {"offset":"+00:00","value":"Europe/Guernsey","text":"(GMT +00:00) Europe/Guernsey"},
    {"offset":"+00:00","value":"Europe/Dublin","text":"(GMT +00:00) Europe/Dublin"},
    {"offset":"+00:00","value":"Africa/Accra","text":"(GMT +00:00) Africa/Accra"},
    {"offset":"+01:00","value":"Europe/Zagreb","text":"(GMT +01:00) Europe/Zagreb"},
    {"offset":"+01:00","value":"Europe/Ljubljana","text":"(GMT +01:00) Europe/Ljubljana"},
    {"offset":"+01:00","value":"Europe/Luxembourg","text":"(GMT +01:00) Europe/Luxembourg"},
    {"offset":"+01:00","value":"Europe/Gibraltar","text":"(GMT +01:00) Europe/Gibraltar"},
    {"offset":"+01:00","value":"Africa/Algiers","text":"(GMT +01:00) Africa/Algiers"},
    {"offset":"+01:00","value":"Europe/Copenhagen","text":"(GMT +01:00) Europe/Copenhagen"},
    {"offset":"+01:00","value":"Europe/Busingen","text":"(GMT +01:00) Europe/Busingen"},
    {"offset":"+01:00","value":"Europe/Budapest","text":"(GMT +01:00) Europe/Budapest"},
    {"offset":"+01:00","value":"Africa/Bangui","text":"(GMT +01:00) Africa/Bangui"},
    {"offset":"+01:00","value":"Europe/Brussels","text":"(GMT +01:00) Europe/Brussels"},
    {"offset":"+01:00","value":"Africa/Brazzaville","text":"(GMT +01:00) Africa/Brazzaville"},
    {"offset":"+01:00","value":"Europe/Bratislava","text":"(GMT +01:00) Europe/Bratislava"},
    {"offset":"+01:00","value":"Europe/Berlin","text":"(GMT +01:00) Europe/Berlin"},
    {"offset":"+01:00","value":"Africa/Ceuta","text":"(GMT +01:00) Africa/Ceuta"},
    {"offset":"+01:00","value":"Europe/Belgrade","text":"(GMT +01:00) Europe/Belgrade"},
    {"offset":"+01:00","value":"Europe/Andorra","text":"(GMT +01:00) Europe/Andorra"},
    {"offset":"+01:00","value":"Europe/Amsterdam","text":"(GMT +01:00) Europe/Amsterdam"},
    {"offset":"+01:00","value":"Europe/Madrid","text":"(GMT +01:00) Europe/Madrid"},
    {"offset":"+01:00","value":"Europe/Malta","text":"(GMT +01:00) Europe/Malta"},
    {"offset":"+01:00","value":"Africa/Douala","text":"(GMT +01:00) Africa/Douala"},
    {"offset":"+01:00","value":"Europe/Monaco","text":"(GMT +01:00) Europe/Monaco"},
    {"offset":"+01:00","value":"Europe/Oslo","text":"(GMT +01:00) Europe/Oslo"},
    {"offset":"+01:00","value":"Europe/Paris","text":"(GMT +01:00) Europe/Paris"},
    {"offset":"+01:00","value":"Europe/Podgorica","text":"(GMT +01:00) Europe/Podgorica"},
    {"offset":"+01:00","value":"Etc/GMT-1","text":"(GMT +01:00) Etc/GMT-1"},
    {"offset":"+01:00","value":"Europe/Prague","text":"(GMT +01:00) Europe/Prague"},
    {"offset":"+01:00","value":"Poland","text":"(GMT +01:00) Poland"},
    {"offset":"+01:00","value":"Europe/Rome","text":"(GMT +01:00) Europe/Rome"},
    {"offset":"+01:00","value":"Europe/San_Marino","text":"(GMT +01:00) Europe/San_Marino"},
    {"offset":"+01:00","value":"Europe/Sarajevo","text":"(GMT +01:00) Europe/Sarajevo"},
    {"offset":"+01:00","value":"Africa/Kinshasa","text":"(GMT +01:00) Africa/Kinshasa"},
    {"offset":"+01:00","value":"Europe/Skopje","text":"(GMT +01:00) Europe/Skopje"},
    {"offset":"+01:00","value":"Europe/Stockholm","text":"(GMT +01:00) Europe/Stockholm"},
    {"offset":"+01:00","value":"Africa/Lagos","text":"(GMT +01:00) Africa/Lagos"},
    {"offset":"+01:00","value":"Africa/Libreville","text":"(GMT +01:00) Africa/Libreville"},
    {"offset":"+01:00","value":"Atlantic/Jan_Mayen","text":"(GMT +01:00) Atlantic/Jan_Mayen"},
    {"offset":"+01:00","value":"Africa/Luanda","text":"(GMT +01:00) Africa/Luanda"},
    {"offset":"+01:00","value":"Europe/Tirane","text":"(GMT +01:00) Europe/Tirane"},
    {"offset":"+01:00","value":"Europe/Vaduz","text":"(GMT +01:00) Europe/Vaduz"},
    {"offset":"+01:00","value":"Europe/Vatican","text":"(GMT +01:00) Europe/Vatican"},
    {"offset":"+01:00","value":"Africa/Malabo","text":"(GMT +01:00) Africa/Malabo"},
    {"offset":"+01:00","value":"Europe/Vienna","text":"(GMT +01:00) Europe/Vienna"},
    {"offset":"+01:00","value":"Europe/Warsaw","text":"(GMT +01:00) Europe/Warsaw"},
    {"offset":"+01:00","value":"CET","text":"(GMT +01:00) CET"},
    {"offset":"+01:00","value":"Europe/Zurich","text":"(GMT +01:00) Europe/Zurich"},
    {"offset":"+01:00","value":"Arctic/Longyearbyen","text":"(GMT +01:00) Arctic/Longyearbyen"},
    {"offset":"+01:00","value":"Africa/Ndjamena","text":"(GMT +01:00) Africa/Ndjamena"},
    {"offset":"+01:00","value":"Africa/Niamey","text":"(GMT +01:00) Africa/Niamey"},
    {"offset":"+01:00","value":"Africa/Porto-Novo","text":"(GMT +01:00) Africa/Porto-Novo"},
    {"offset":"+01:00","value":"MET","text":"(GMT +01:00) MET"},
    {"offset":"+01:00","value":"Africa/Tunis","text":"(GMT +01:00) Africa/Tunis"},
    {"offset":"+02:00","value":"Africa/Windhoek","text":"(GMT +02:00) Africa/Windhoek"},
    {"offset":"+02:00","value":"Asia/Amman","text":"(GMT +02:00) Asia/Amman"},
    {"offset":"+02:00","value":"Libya","text":"(GMT +02:00) Libya"},
    {"offset":"+02:00","value":"Israel","text":"(GMT +02:00) Israel"},
    {"offset":"+02:00","value":"Europe/Kiev","text":"(GMT +02:00) Europe/Kiev"},
    {"offset":"+02:00","value":"Europe/Kaliningrad","text":"(GMT +02:00) Europe/Kaliningrad"},
    {"offset":"+02:00","value":"Europe/Istanbul","text":"(GMT +02:00) Europe/Istanbul"},
    {"offset":"+02:00","value":"Europe/Helsinki","text":"(GMT +02:00) Europe/Helsinki"},
    {"offset":"+02:00","value":"Europe/Chisinau","text":"(GMT +02:00) Europe/Chisinau"},
    {"offset":"+02:00","value":"Europe/Bucharest","text":"(GMT +02:00) Europe/Bucharest"},
    {"offset":"+02:00","value":"Africa/Blantyre","text":"(GMT +02:00) Africa/Blantyre"},
    {"offset":"+02:00","value":"Africa/Bujumbura","text":"(GMT +02:00) Africa/Bujumbura"},
    {"offset":"+02:00","value":"Africa/Cairo","text":"(GMT +02:00) Africa/Cairo"},
    {"offset":"+02:00","value":"Europe/Athens","text":"(GMT +02:00) Europe/Athens"},
    {"offset":"+02:00","value":"Africa/Mbabane","text":"(GMT +02:00) Africa/Mbabane"},
    {"offset":"+02:00","value":"Europe/Zaporozhye","text":"(GMT +02:00) Europe/Zaporozhye"},
    {"offset":"+02:00","value":"Asia/Tel_Aviv","text":"(GMT +02:00) Asia/Tel_Aviv"},
    {"offset":"+02:00","value":"Africa/Maseru","text":"(GMT +02:00) Africa/Maseru"},
    {"offset":"+02:00","value":"Asia/Beirut","text":"(GMT +02:00) Asia/Beirut"},
    {"offset":"+02:00","value":"Europe/Mariehamn","text":"(GMT +02:00) Europe/Mariehamn"},
    {"offset":"+02:00","value":"Asia/Jerusalem","text":"(GMT +02:00) Asia/Jerusalem"},
    {"offset":"+02:00","value":"Europe/Vilnius","text":"(GMT +02:00) Europe/Vilnius"},
    {"offset":"+02:00","value":"Africa/Maputo","text":"(GMT +02:00) Africa/Maputo"},
    {"offset":"+02:00","value":"Asia/Istanbul","text":"(GMT +02:00) Asia/Istanbul"},
    {"offset":"+02:00","value":"Africa/Gaborone","text":"(GMT +02:00) Africa/Gaborone"},
    {"offset":"+02:00","value":"Africa/Lusaka","text":"(GMT +02:00) Africa/Lusaka"},
    {"offset":"+02:00","value":"Europe/Uzhgorod","text":"(GMT +02:00) Europe/Uzhgorod"},
    {"offset":"+02:00","value":"EET","text":"(GMT +02:00) EET"},
    {"offset":"+02:00","value":"Europe/Tiraspol","text":"(GMT +02:00) Europe/Tiraspol"},
    {"offset":"+02:00","value":"Asia/Hebron","text":"(GMT +02:00) Asia/Hebron"},
    {"offset":"+02:00","value":"Egypt","text":"(GMT +02:00) Egypt"},
    {"offset":"+02:00","value":"Africa/Lubumbashi","text":"(GMT +02:00) Africa/Lubumbashi"},
    {"offset":"+02:00","value":"Asia/Gaza","text":"(GMT +02:00) Asia/Gaza"},
    {"offset":"+02:00","value":"Etc/GMT-2","text":"(GMT +02:00) Etc/GMT-2"},
    {"offset":"+02:00","value":"Europe/Tallinn","text":"(GMT +02:00) Europe/Tallinn"},
    {"offset":"+02:00","value":"Europe/Nicosia","text":"(GMT +02:00) Europe/Nicosia"},
    {"offset":"+02:00","value":"Asia/Damascus","text":"(GMT +02:00) Asia/Damascus"},
    {"offset":"+02:00","value":"Europe/Sofia","text":"(GMT +02:00) Europe/Sofia"},
    {"offset":"+02:00","value":"Asia/Nicosia","text":"(GMT +02:00) Asia/Nicosia"},
    {"offset":"+02:00","value":"Africa/Harare","text":"(GMT +02:00) Africa/Harare"},
    {"offset":"+02:00","value":"Africa/Kigali","text":"(GMT +02:00) Africa/Kigali"},
    {"offset":"+02:00","value":"Africa/Johannesburg","text":"(GMT +02:00) Africa/Johannesburg"},
    {"offset":"+02:00","value":"Africa/Tripoli","text":"(GMT +02:00) Africa/Tripoli"},
    {"offset":"+02:00","value":"Turkey","text":"(GMT +02:00) Turkey"},
    {"offset":"+02:00","value":"Europe/Riga","text":"(GMT +02:00) Europe/Riga"},
    {"offset":"+03:00","value":"Africa/Addis_Ababa","text":"(GMT +03:00) Africa/Addis_Ababa"},
    {"offset":"+03:00","value":"Africa/Kampala","text":"(GMT +03:00) Africa/Kampala"},
    {"offset":"+03:00","value":"Africa/Juba","text":"(GMT +03:00) Africa/Juba"},
    {"offset":"+03:00","value":"Asia/Aden","text":"(GMT +03:00) Asia/Aden"},
    {"offset":"+03:00","value":"Europe/Simferopol","text":"(GMT +03:00) Europe/Simferopol"},
    {"offset":"+03:00","value":"Indian/Mayotte","text":"(GMT +03:00) Indian/Mayotte"},
    {"offset":"+03:00","value":"Europe/Moscow","text":"(GMT +03:00) Europe/Moscow"},
    {"offset":"+03:00","value":"W-SU","text":"(GMT +03:00) W-SU"},
    {"offset":"+03:00","value":"Etc/GMT-3","text":"(GMT +03:00) Etc/GMT-3"},
    {"offset":"+03:00","value":"Asia/Qatar","text":"(GMT +03:00) Asia/Qatar"},
    {"offset":"+03:00","value":"Asia/Kuwait","text":"(GMT +03:00) Asia/Kuwait"},
    {"offset":"+03:00","value":"Europe/Minsk","text":"(GMT +03:00) Europe/Minsk"},
    {"offset":"+03:00","value":"Africa/Asmara","text":"(GMT +03:00) Africa/Asmara"},
    {"offset":"+03:00","value":"Africa/Djibouti","text":"(GMT +03:00) Africa/Djibouti"},
    {"offset":"+03:00","value":"Europe/Volgograd","text":"(GMT +03:00) Europe/Volgograd"},
    {"offset":"+03:00","value":"Africa/Dar_es_Salaam","text":"(GMT +03:00) Africa/Dar_es_Salaam"},
    {"offset":"+03:00","value":"Asia/Riyadh","text":"(GMT +03:00) Asia/Riyadh"},
    {"offset":"+03:00","value":"Asia/Bahrain","text":"(GMT +03:00) Asia/Bahrain"},
    {"offset":"+03:00","value":"Asia/Baghdad","text":"(GMT +03:00) Asia/Baghdad"},
    {"offset":"+03:00","value":"Africa/Khartoum","text":"(GMT +03:00) Africa/Khartoum"},
    {"offset":"+03:00","value":"Africa/Asmera","text":"(GMT +03:00) Africa/Asmera"},
    {"offset":"+03:00","value":"Africa/Mogadishu","text":"(GMT +03:00) Africa/Mogadishu"},
    {"offset":"+03:00","value":"Indian/Comoro","text":"(GMT +03:00) Indian/Comoro"},
    {"offset":"+03:00","value":"Africa/Nairobi","text":"(GMT +03:00) Africa/Nairobi"},
    {"offset":"+03:00","value":"Antarctica/Syowa","text":"(GMT +03:00) Antarctica/Syowa"},
    {"offset":"+03:00","value":"Indian/Antananarivo","text":"(GMT +03:00) Indian/Antananarivo"},
    {"offset":"+03:30","value":"Iran","text":"(GMT +03:30) Iran"},
    {"offset":"+03:30","value":"Asia/Tehran","text":"(GMT +03:30) Asia/Tehran"},
    {"offset":"+04:00","value":"Indian/Mauritius","text":"(GMT +04:00) Indian/Mauritius"},
    {"offset":"+04:00","value":"Indian/Mahe","text":"(GMT +04:00) Indian/Mahe"},
    {"offset":"+04:00","value":"Asia/Tbilisi","text":"(GMT +04:00) Asia/Tbilisi"},
    {"offset":"+04:00","value":"Etc/GMT-4","text":"(GMT +04:00) Etc/GMT-4"},
    {"offset":"+04:00","value":"Asia/Baku","text":"(GMT +04:00) Asia/Baku"},
    {"offset":"+04:00","value":"Asia/Dubai","text":"(GMT +04:00) Asia/Dubai"},
    {"offset":"+04:00","value":"Asia/Muscat","text":"(GMT +04:00) Asia/Muscat"},
    {"offset":"+04:00","value":"Asia/Yerevan","text":"(GMT +04:00) Asia/Yerevan"},
    {"offset":"+04:00","value":"Indian/Reunion","text":"(GMT +04:00) Indian/Reunion"},
    {"offset":"+04:00","value":"Europe/Samara","text":"(GMT +04:00) Europe/Samara"},
    {"offset":"+04:30","value":"Asia/Kabul","text":"(GMT +04:30) Asia/Kabul"},
    {"offset":"+05:00","value":"Indian/Maldives","text":"(GMT +05:00) Indian/Maldives"},
    {"offset":"+05:00","value":"Asia/Yekaterinburg","text":"(GMT +05:00) Asia/Yekaterinburg"},
    {"offset":"+05:00","value":"Asia/Ashkhabad","text":"(GMT +05:00) Asia/Ashkhabad"},
    {"offset":"+05:00","value":"Etc/GMT-5","text":"(GMT +05:00) Etc/GMT-5"},
    {"offset":"+05:00","value":"Asia/Aqtobe","text":"(GMT +05:00) Asia/Aqtobe"},
    {"offset":"+05:00","value":"Indian/Kerguelen","text":"(GMT +05:00) Indian/Kerguelen"},
    {"offset":"+05:00","value":"Asia/Aqtau","text":"(GMT +05:00) Asia/Aqtau"},
    {"offset":"+05:00","value":"Asia/Tashkent","text":"(GMT +05:00) Asia/Tashkent"},
    {"offset":"+05:00","value":"Asia/Ashgabat","text":"(GMT +05:00) Asia/Ashgabat"},
    {"offset":"+05:00","value":"Asia/Samarkand","text":"(GMT +05:00) Asia/Samarkand"},
    {"offset":"+05:00","value":"Antarctica/Mawson","text":"(GMT +05:00) Antarctica/Mawson"},
    {"offset":"+05:00","value":"Asia/Dushanbe","text":"(GMT +05:00) Asia/Dushanbe"},
    {"offset":"+05:00","value":"Asia/Karachi","text":"(GMT +05:00) Asia/Karachi"},
    {"offset":"+05:00","value":"Asia/Oral","text":"(GMT +05:00) Asia/Oral"},
    {"offset":"+05:30","value":"Asia/Kolkata","text":"(GMT +05:30) Asia/Kolkata"},
    {"offset":"+05:30","value":"Asia/Calcutta","text":"(GMT +05:30) Asia/Calcutta"},
    {"offset":"+05:30","value":"Asia/Colombo","text":"(GMT +05:30) Asia/Colombo"},
    {"offset":"+05:45","value":"Asia/Katmandu","text":"(GMT +05:45) Asia/Katmandu"},
    {"offset":"+05:45","value":"Asia/Kathmandu","text":"(GMT +05:45) Asia/Kathmandu"},
    {"offset":"+06:00","value":"Asia/Almaty","text":"(GMT +06:00) Asia/Almaty"},
    {"offset":"+06:00","value":"Asia/Novosibirsk","text":"(GMT +06:00) Asia/Novosibirsk"},
    {"offset":"+06:00","value":"Etc/GMT-6","text":"(GMT +06:00) Etc/GMT-6"},
    {"offset":"+06:00","value":"Indian/Chagos","text":"(GMT +06:00) Indian/Chagos"},
    {"offset":"+06:00","value":"Antarctica/Vostok","text":"(GMT +06:00) Antarctica/Vostok"},
    {"offset":"+06:00","value":"Asia/Omsk","text":"(GMT +06:00) Asia/Omsk"},
    {"offset":"+06:00","value":"Asia/Qyzylorda","text":"(GMT +06:00) Asia/Qyzylorda"},
    {"offset":"+06:00","value":"Asia/Thimbu","text":"(GMT +06:00) Asia/Thimbu"},
    {"offset":"+06:00","value":"Asia/Bishkek","text":"(GMT +06:00) Asia/Bishkek"},
    {"offset":"+06:00","value":"Asia/Kashgar","text":"(GMT +06:00) Asia/Kashgar"},
    {"offset":"+06:00","value":"Asia/Thimphu","text":"(GMT +06:00) Asia/Thimphu"},
    {"offset":"+06:00","value":"Asia/Dhaka","text":"(GMT +06:00) Asia/Dhaka"},
    {"offset":"+06:00","value":"Asia/Dacca","text":"(GMT +06:00) Asia/Dacca"},
    {"offset":"+06:00","value":"Asia/Urumqi","text":"(GMT +06:00) Asia/Urumqi"},
    {"offset":"+06:30","value":"Asia/Rangoon","text":"(GMT +06:30) Asia/Rangoon"},
    {"offset":"+06:30","value":"Indian/Cocos","text":"(GMT +06:30) Indian/Cocos"},
    {"offset":"+07:00","value":"Asia/Saigon","text":"(GMT +07:00) Asia/Saigon"},
    {"offset":"+07:00","value":"Asia/Jakarta","text":"(GMT +07:00) Asia/Jakarta"},
    {"offset":"+07:00","value":"Asia/Pontianak","text":"(GMT +07:00) Asia/Pontianak"},
    {"offset":"+07:00","value":"Asia/Vientiane","text":"(GMT +07:00) Asia/Vientiane"},
    {"offset":"+07:00","value":"Asia/Bangkok","text":"(GMT +07:00) Asia/Bangkok"},
    {"offset":"+07:00","value":"Asia/Krasnoyarsk","text":"(GMT +07:00) Asia/Krasnoyarsk"},
    {"offset":"+07:00","value":"Asia/Ho_Chi_Minh","text":"(GMT +07:00) Asia/Ho_Chi_Minh"},
    {"offset":"+07:00","value":"Etc/GMT-7","text":"(GMT +07:00) Etc/GMT-7"},
    {"offset":"+07:00","value":"Antarctica/Davis","text":"(GMT +07:00) Antarctica/Davis"},
    {"offset":"+07:00","value":"Asia/Novokuznetsk","text":"(GMT +07:00) Asia/Novokuznetsk"},
    {"offset":"+07:00","value":"Indian/Christmas","text":"(GMT +07:00) Indian/Christmas"},
    {"offset":"+07:00","value":"Asia/Hovd","text":"(GMT +07:00) Asia/Hovd"},
    {"offset":"+07:00","value":"Asia/Phnom_Penh","text":"(GMT +07:00) Asia/Phnom_Penh"},
    {"offset":"+08:00","value":"Australia/West","text":"(GMT +08:00) Australia/West"},
    {"offset":"+08:00","value":"Asia/Irkutsk","text":"(GMT +08:00) Asia/Irkutsk"},
    {"offset":"+08:00","value":"Asia/Harbin","text":"(GMT +08:00) Asia/Harbin"},
    {"offset":"+08:00","value":"Asia/Ulan_Bator","text":"(GMT +08:00) Asia/Ulan_Bator"},
    {"offset":"+08:00","value":"Asia/Kuala_Lumpur","text":"(GMT +08:00) Asia/Kuala_Lumpur"},
    {"offset":"+08:00","value":"Singapore","text":"(GMT +08:00) Singapore"},
    {"offset":"+08:00","value":"Hongkong","text":"(GMT +08:00) Hongkong"},
    {"offset":"+08:00","value":"Asia/Chungking","text":"(GMT +08:00) Asia/Chungking"},
    {"offset":"+08:00","value":"Asia/Brunei","text":"(GMT +08:00) Asia/Brunei"},
    {"offset":"+08:00","value":"Asia/Ulaanbaatar","text":"(GMT +08:00) Asia/Ulaanbaatar"},
    {"offset":"+08:00","value":"Asia/Hong_Kong","text":"(GMT +08:00) Asia/Hong_Kong"},
    {"offset":"+08:00","value":"Asia/Macao","text":"(GMT +08:00) Asia/Macao"},
    {"offset":"+08:00","value":"Asia/Chita","text":"(GMT +08:00) Asia/Chita"},
    {"offset":"+08:00","value":"Asia/Manila","text":"(GMT +08:00) Asia/Manila"},
    {"offset":"+08:00","value":"Asia/Ujung_Pandang","text":"(GMT +08:00) Asia/Ujung_Pandang"},
    {"offset":"+08:00","value":"Australia/Perth","text":"(GMT +08:00) Australia/Perth"},
    {"offset":"+08:00","value":"Antarctica/Casey","text":"(GMT +08:00) Antarctica/Casey"},
    {"offset":"+08:00","value":"Asia/Chongqing","text":"(GMT +08:00) Asia/Chongqing"},
    {"offset":"+08:00","value":"Asia/Shanghai","text":"(GMT +08:00) Asia/Shanghai"},
    {"offset":"+08:00","value":"Asia/Makassar","text":"(GMT +08:00) Asia/Makassar"},
    {"offset":"+08:00","value":"ROC","text":"(GMT +08:00) ROC"},
    {"offset":"+08:00","value":"Asia/Choibalsan","text":"(GMT +08:00) Asia/Choibalsan"},
    {"offset":"+08:00","value":"Asia/Singapore","text":"(GMT +08:00) Asia/Singapore"},
    {"offset":"+08:00","value":"Asia/Macau","text":"(GMT +08:00) Asia/Macau"},
    {"offset":"+08:00","value":"PRC","text":"(GMT +08:00) PRC"},
    {"offset":"+08:00","value":"Asia/Taipei","text":"(GMT +08:00) Asia/Taipei"},
    {"offset":"+08:00","value":"Asia/Kuching","text":"(GMT +08:00) Asia/Kuching"},
    {"offset":"+08:00","value":"Etc/GMT-8","text":"(GMT +08:00) Etc/GMT-8"},
    {"offset":"+08:45","value":"Australia/Eucla","text":"(GMT +08:45) Australia/Eucla"},
    {"offset":"+09:00","value":"ROK","text":"(GMT +09:00) ROK"},
    {"offset":"+09:00","value":"Japan","text":"(GMT +09:00) Japan"},
    {"offset":"+09:00","value":"Asia/Tokyo","text":"(GMT +09:00) Asia/Tokyo"},
    {"offset":"+09:00","value":"Pacific/Palau","text":"(GMT +09:00) Pacific/Palau"},
    {"offset":"+09:00","value":"Etc/GMT-9","text":"(GMT +09:00) Etc/GMT-9"},
    {"offset":"+09:00","value":"Asia/Yakutsk","text":"(GMT +09:00) Asia/Yakutsk"},
    {"offset":"+09:00","value":"Asia/Pyongyang","text":"(GMT +09:00) Asia/Pyongyang"},
    {"offset":"+09:00","value":"Asia/Khandyga","text":"(GMT +09:00) Asia/Khandyga"},
    {"offset":"+09:00","value":"Asia/Jayapura","text":"(GMT +09:00) Asia/Jayapura"},
    {"offset":"+09:00","value":"Asia/Dili","text":"(GMT +09:00) Asia/Dili"},
    {"offset":"+09:00","value":"Asia/Seoul","text":"(GMT +09:00) Asia/Seoul"},
    {"offset":"+09:30","value":"Australia/Darwin","text":"(GMT +09:30) Australia/Darwin"},
    {"offset":"+09:30","value":"Australia/North","text":"(GMT +09:30) Australia/North"},
    {"offset":"+10:00","value":"Asia/Ust-Nera","text":"(GMT +10:00) Asia/Ust-Nera"},
    {"offset":"+10:00","value":"Pacific/Yap","text":"(GMT +10:00) Pacific/Yap"},
    {"offset":"+10:00","value":"Pacific/Truk","text":"(GMT +10:00) Pacific/Truk"},
    {"offset":"+10:00","value":"Australia/Brisbane","text":"(GMT +10:00) Australia/Brisbane"},
    {"offset":"+10:00","value":"Asia/Vladivostok","text":"(GMT +10:00) Asia/Vladivostok"},
    {"offset":"+10:00","value":"Asia/Magadan","text":"(GMT +10:00) Asia/Magadan"},
    {"offset":"+10:00","value":"Pacific/Chuuk","text":"(GMT +10:00) Pacific/Chuuk"},
    {"offset":"+10:00","value":"Australia/Lindeman","text":"(GMT +10:00) Australia/Lindeman"},
    {"offset":"+10:00","value":"Australia/Queensland","text":"(GMT +10:00) Australia/Queensland"},
    {"offset":"+10:00","value":"Pacific/Guam","text":"(GMT +10:00) Pacific/Guam"},
    {"offset":"+10:00","value":"Pacific/Port_Moresby","text":"(GMT +10:00) Pacific/Port_Moresby"},
    {"offset":"+10:00","value":"Etc/GMT-10","text":"(GMT +10:00) Etc/GMT-10"},
    {"offset":"+10:00","value":"Pacific/Saipan","text":"(GMT +10:00) Pacific/Saipan"},
    {"offset":"+10:00","value":"Antarctica/DumontDUrville","text":"(GMT +10:00) Antarctica/DumontDUrville"},
    {"offset":"+10:00","value":"Asia/Sakhalin","text":"(GMT +10:00) Asia/Sakhalin"},
    {"offset":"+10:30","value":"Australia/Yancowinna","text":"(GMT +10:30) Australia/Yancowinna"},
    {"offset":"+10:30","value":"Australia/Broken_Hill","text":"(GMT +10:30) Australia/Broken_Hill"},
    {"offset":"+10:30","value":"Australia/Adelaide","text":"(GMT +10:30) Australia/Adelaide"},
    {"offset":"+10:30","value":"Australia/South","text":"(GMT +10:30) Australia/South"},
    {"offset":"+11:00","value":"Etc/GMT-11","text":"(GMT +11:00) Etc/GMT-11"},
    {"offset":"+11:00","value":"Australia/LHI","text":"(GMT +11:00) Australia/LHI"},
    {"offset":"+11:00","value":"Australia/Hobart","text":"(GMT +11:00) Australia/Hobart"},
    {"offset":"+11:00","value":"Australia/Currie","text":"(GMT +11:00) Australia/Currie"},
    {"offset":"+11:00","value":"Australia/Victoria","text":"(GMT +11:00) Australia/Victoria"},
    {"offset":"+11:00","value":"Pacific/Noumea","text":"(GMT +11:00) Pacific/Noumea"},
    {"offset":"+11:00","value":"Australia/NSW","text":"(GMT +11:00) Australia/NSW"},
    {"offset":"+11:00","value":"Asia/Srednekolymsk","text":"(GMT +11:00) Asia/Srednekolymsk"},
    {"offset":"+11:00","value":"Australia/Tasmania","text":"(GMT +11:00) Australia/Tasmania"},
    {"offset":"+11:00","value":"Pacific/Pohnpei","text":"(GMT +11:00) Pacific/Pohnpei"},
    {"offset":"+11:00","value":"Pacific/Ponape","text":"(GMT +11:00) Pacific/Ponape"},
    {"offset":"+11:00","value":"Australia/Sydney","text":"(GMT +11:00) Australia/Sydney"},
    {"offset":"+11:00","value":"Pacific/Guadalcanal","text":"(GMT +11:00) Pacific/Guadalcanal"},
    {"offset":"+11:00","value":"Australia/Canberra","text":"(GMT +11:00) Australia/Canberra"},
    {"offset":"+11:00","value":"Australia/ACT","text":"(GMT +11:00) Australia/ACT"},
    {"offset":"+11:00","value":"Antarctica/Macquarie","text":"(GMT +11:00) Antarctica/Macquarie"},
    {"offset":"+11:00","value":"Australia/Melbourne","text":"(GMT +11:00) Australia/Melbourne"},
    {"offset":"+11:00","value":"Pacific/Kosrae","text":"(GMT +11:00) Pacific/Kosrae"},
    {"offset":"+11:00","value":"Pacific/Bougainville","text":"(GMT +11:00) Pacific/Bougainville"},
    {"offset":"+11:00","value":"Australia/Lord_Howe","text":"(GMT +11:00) Australia/Lord_Howe"},
    {"offset":"+11:00","value":"Pacific/Efate","text":"(GMT +11:00) Pacific/Efate"},
    {"offset":"+11:30","value":"Pacific/Norfolk","text":"(GMT +11:30) Pacific/Norfolk"},
    {"offset":"+12:00","value":"Asia/Kamchatka","text":"(GMT +12:00) Asia/Kamchatka"},
    {"offset":"+12:00","value":"Pacific/Tarawa","text":"(GMT +12:00) Pacific/Tarawa"},
    {"offset":"+12:00","value":"Pacific/Wallis","text":"(GMT +12:00) Pacific/Wallis"},
    {"offset":"+12:00","value":"Pacific/Nauru","text":"(GMT +12:00) Pacific/Nauru"},
    {"offset":"+12:00","value":"Pacific/Majuro","text":"(GMT +12:00) Pacific/Majuro"},
    {"offset":"+12:00","value":"Pacific/Kwajalein","text":"(GMT +12:00) Pacific/Kwajalein"},
    {"offset":"+12:00","value":"Etc/GMT-12","text":"(GMT +12:00) Etc/GMT-12"},
    {"offset":"+12:00","value":"Pacific/Funafuti","text":"(GMT +12:00) Pacific/Funafuti"},
    {"offset":"+12:00","value":"Asia/Anadyr","text":"(GMT +12:00) Asia/Anadyr"},
    {"offset":"+12:00","value":"Kwajalein","text":"(GMT +12:00) Kwajalein"},
    {"offset":"+12:00","value":"Pacific/Wake","text":"(GMT +12:00) Pacific/Wake"},
    {"offset":"+13:00","value":"Antarctica/McMurdo","text":"(GMT +13:00) Antarctica/McMurdo"},
    {"offset":"+13:00","value":"Pacific/Enderbury","text":"(GMT +13:00) Pacific/Enderbury"},
    {"offset":"+13:00","value":"Pacific/Tongatapu","text":"(GMT +13:00) Pacific/Tongatapu"},
    {"offset":"+13:00","value":"Pacific/Fiji","text":"(GMT +13:00) Pacific/Fiji"},
    {"offset":"+13:00","value":"NZ","text":"(GMT +13:00) NZ"},
    {"offset":"+13:00","value":"Pacific/Fakaofo","text":"(GMT +13:00) Pacific/Fakaofo"},
    {"offset":"+13:00","value":"Etc/GMT-13","text":"(GMT +13:00) Etc/GMT-13"},
    {"offset":"+13:00","value":"Pacific/Auckland","text":"(GMT +13:00) Pacific/Auckland"},
    {"offset":"+13:00","value":"Antarctica/South_Pole","text":"(GMT +13:00) Antarctica/South_Pole"},
    {"offset":"+13:45","value":"NZ-CHAT","text":"(GMT +13:45) NZ-CHAT"},
    {"offset":"+13:45","value":"Pacific/Chatham","text":"(GMT +13:45) Pacific/Chatham"},
    {"offset":"+14:00","value":"Etc/GMT-14","text":"(GMT +14:00) Etc/GMT-14"},
    {"offset":"+14:00","value":"Pacific/Kiritimati","text":"(GMT +14:00) Pacific/Kiritimati"},
    {"offset":"+14:00","value":"Pacific/Apia","text":"(GMT +14:00) Pacific/Apia"}
  ])
  .constant('COUNTRIES',[
    {id:"AF",text:"Afghanistan"},
    {id:"AX",text:"Åland Islands"},
    {id:"AL",text:"Albania"},
    {id:"DZ",text:"Algeria"},
    {id:"AS",text:"American Samoa"},
    {id:"AD",text:"Andorra"},
    {id:"AO",text:"Angola"},
    {id:"AI",text:"Anguilla"},
    {id:"AQ",text:"Antarctica"},
    {id:"AG",text:"Antigua and Barbuda"},
    {id:"AR",text:"Argentina"},
    {id:"AM",text:"Armenia"},
    {id:"AW",text:"Aruba"},
    {id:"AU",text:"Australia"},
    {id:"AT",text:"Austria"},
    {id:"AZ",text:"Azerbaijan"},
    {id:"BS",text:"Bahamas"},
    {id:"BH",text:"Bahrain"},
    {id:"BD",text:"Bangladesh"},
    {id:"BB",text:"Barbados"},
    {id:"BY",text:"Belarus"},
    {id:"BE",text:"Belgium"},
    {id:"BZ",text:"Belize"},
    {id:"BJ",text:"Benin"},
    {id:"BM",text:"Bermuda"},
    {id:"BT",text:"Bhutan"},
    {id:"BO",text:"Bolivia, Plurinational State of"},
    {id:"BQ",text:"Bonaire, Sint Eustatius and Saba"},
    {id:"BA",text:"Bosnia and Herzegovina"},
    {id:"BW",text:"Botswana"},
    {id:"BV",text:"Bouvet Island"},
    {id:"BR",text:"Brazil"},
    {id:"IO",text:"British Indian Ocean Territory"},
    {id:"BN",text:"Brunei Darussalam"},
    {id:"BG",text:"Bulgaria"},
    {id:"BF",text:"Burkina Faso"},
    {id:"BI",text:"Burundi"},
    {id:"KH",text:"Cambodia"},
    {id:"CM",text:"Cameroon"},
    {id:"CA",text:"Canada"},
    {id:"CV",text:"Cape Verde"},
    {id:"KY",text:"Cayman Islands"},
    {id:"CF",text:"Central African Republic"},
    {id:"TD",text:"Chad"},
    {id:"CL",text:"Chile"},
    {id:"CN",text:"China"},
    {id:"CX",text:"Christmas Island"},
    {id:"CC",text:"Cocos (Keeling) Islands"},
    {id:"CO",text:"Colombia"},
    {id:"KM",text:"Comoros"},
    {id:"CG",text:"Congo"},
    {id:"CD",text:"Congo, the Democratic Republic of the"},
    {id:"CK",text:"Cook Islands"},
    {id:"CR",text:"Costa Rica"},
    {id:"CI",text:"Côte d'Ivoire"},
    {id:"HR",text:"Croatia"},
    {id:"CU",text:"Cuba"},
    {id:"CW",text:"Curaçao"},
    {id:"CY",text:"Cyprus"},
    {id:"CZ",text:"Czech Republic"},
    {id:"DK",text:"Denmark"},
    {id:"DJ",text:"Djibouti"},
    {id:"DM",text:"Dominica"},
    {id:"DO",text:"Dominican Republic"},
    {id:"EC",text:"Ecuador"},
    {id:"EG",text:"Egypt"},
    {id:"SV",text:"El Salvador"},
    {id:"GQ",text:"Equatorial Guinea"},
    {id:"ER",text:"Eritrea"},
    {id:"EE",text:"Estonia"},
    {id:"ET",text:"Ethiopia"},
    {id:"FK",text:"Falkland Islands (Malvinas)"},
    {id:"FO",text:"Faroe Islands"},
    {id:"FJ",text:"Fiji"},
    {id:"FI",text:"Finland"},
    {id:"FR",text:"France"},
    {id:"GF",text:"French Guiana"},
    {id:"PF",text:"French Polynesia"},
    {id:"TF",text:"French Southern Territories"},
    {id:"GA",text:"Gabon"},
    {id:"GM",text:"Gambia"},
    {id:"GE",text:"Georgia"},
    {id:"DE",text:"Germany"},
    {id:"GH",text:"Ghana"},
    {id:"GI",text:"Gibraltar"},
    {id:"GR",text:"Greece"},
    {id:"GL",text:"Greenland"},
    {id:"GD",text:"Grenada"},
    {id:"GP",text:"Guadeloupe"},
    {id:"GU",text:"Guam"},
    {id:"GT",text:"Guatemala"},
    {id:"GG",text:"Guernsey"},
    {id:"GN",text:"Guinea"},
    {id:"GW",text:"Guinea-Bissau"},
    {id:"GY",text:"Guyana"},
    {id:"HT",text:"Haiti"},
    {id:"HM",text:"Heard Island and McDonald Islands"},
    {id:"VA",text:"Holy See (Vatican City State)"},
    {id:"HN",text:"Honduras"},
    {id:"HK",text:"Hong Kong"},
    {id:"HU",text:"Hungary"},
    {id:"IS",text:"Iceland"},
    {id:"IN",text:"India"},
    {id:"ID",text:"Indonesia"},
    {id:"IR",text:"Iran, Islamic Republic of"},
    {id:"IQ",text:"Iraq"},
    {id:"IE",text:"Ireland"},
    {id:"IM",text:"Isle of Man"},
    {id:"IL",text:"Israel"},
    {id:"IT",text:"Italy"},
    {id:"JM",text:"Jamaica"},
    {id:"JP",text:"Japan"},
    {id:"JE",text:"Jersey"},
    {id:"JO",text:"Jordan"},
    {id:"KZ",text:"Kazakhstan"},
    {id:"KE",text:"Kenya"},
    {id:"KI",text:"Kiribati"},
    {id:"KP",text:"Korea, Democratic People's Republic of"},
    {id:"KR",text:"Korea, Republic of"},
    {id:"KW",text:"Kuwait"},
    {id:"KG",text:"Kyrgyzstan"},
    {id:"LA",text:"Lao People's Democratic Republic"},
    {id:"LV",text:"Latvia"},
    {id:"LB",text:"Lebanon"},
    {id:"LS",text:"Lesotho"},
    {id:"LR",text:"Liberia"},
    {id:"LY",text:"Libya"},
    {id:"LI",text:"Liechtenstein"},
    {id:"LT",text:"Lithuania"},
    {id:"LU",text:"Luxembourg"},
    {id:"MO",text:"Macao"},
    {id:"MK",text:"Macedonia, the former Yugoslav Republic of"},
    {id:"MG",text:"Madagascar"},
    {id:"MW",text:"Malawi"},
    {id:"MY",text:"Malaysia"},
    {id:"MV",text:"Maldives"},
    {id:"ML",text:"Mali"},
    {id:"MT",text:"Malta"},
    {id:"MH",text:"Marshall Islands"},
    {id:"MQ",text:"Martinique"},
    {id:"MR",text:"Mauritania"},
    {id:"MU",text:"Mauritius"},
    {id:"YT",text:"Mayotte"},
    {id:"MX",text:"Mexico"},
    {id:"FM",text:"Micronesia, Federated States of"},
    {id:"MD",text:"Moldova, Republic of"},
    {id:"MC",text:"Monaco"},
    {id:"MN",text:"Mongolia"},
    {id:"ME",text:"Montenegro"},
    {id:"MS",text:"Montserrat"},
    {id:"MA",text:"Morocco"},
    {id:"MZ",text:"Mozambique"},
    {id:"MM",text:"Myanmar"},
    {id:"NA",text:"Namibia"},
    {id:"NR",text:"Nauru"},
    {id:"NP",text:"Nepal"},
    {id:"NL",text:"Netherlands"},
    {id:"NC",text:"New Caledonia"},
    {id:"NZ",text:"New Zealand"},
    {id:"NI",text:"Nicaragua"},
    {id:"NE",text:"Niger"},
    {id:"NG",text:"Nigeria"},
    {id:"NU",text:"Niue"},
    {id:"NF",text:"Norfolk Island"},
    {id:"MP",text:"Northern Mariana Islands"},
    {id:"NO",text:"Norway"},
    {id:"OM",text:"Oman"},
    {id:"PK",text:"Pakistan"},
    {id:"PW",text:"Palau"},
    {id:"PS",text:"Palestinian Territory, Occupied"},
    {id:"PA",text:"Panama"},
    {id:"PG",text:"Papua New Guinea"},
    {id:"PY",text:"Paraguay"},
    {id:"PE",text:"Peru"},
    {id:"PH",text:"Philippines"},
    {id:"PN",text:"Pitcairn"},
    {id:"PL",text:"Poland"},
    {id:"PT",text:"Portugal"},
    {id:"PR",text:"Puerto Rico"},
    {id:"QA",text:"Qatar"},
    {id:"RE",text:"Réunion"},
    {id:"RO",text:"Romania"},
    {id:"RU",text:"Russian Federation"},
    {id:"RW",text:"Rwanda"},
    {id:"BL",text:"Saint Barthélemy"},
    {id:"SH",text:"Saint Helena, Ascension and Tristan da Cunha"},
    {id:"KN",text:"Saint Kitts and Nevis"},
    {id:"LC",text:"Saint Lucia"},
    {id:"MF",text:"Saint Martin (French part)"},
    {id:"PM",text:"Saint Pierre and Miquelon"},
    {id:"VC",text:"Saint Vincent and the Grenadines"},
    {id:"WS",text:"Samoa"},
    {id:"SM",text:"San Marino"},
    {id:"ST",text:"Sao Tome and Principe"},
    {id:"SA",text:"Saudi Arabia"},
    {id:"SN",text:"Senegal"},
    {id:"RS",text:"Serbia"},
    {id:"SC",text:"Seychelles"},
    {id:"SL",text:"Sierra Leone"},
    {id:"SG",text:"Singapore"},
    {id:"SX",text:"Sint Maarten (Dutch part)"},
    {id:"SK",text:"Slovakia"},
    {id:"SI",text:"Slovenia"},
    {id:"SB",text:"Solomon Islands"},
    {id:"SO",text:"Somalia"},
    {id:"ZA",text:"South Africa"},
    {id:"GS",text:"South Georgia and the South Sandwich Islands"},
    {id:"SS",text:"South Sudan"},
    {id:"ES",text:"Spain"},
    {id:"LK",text:"Sri Lanka"},
    {id:"SD",text:"Sudan"},
    {id:"SR",text:"Suriname"},
    {id:"SJ",text:"Svalbard and Jan Mayen"},
    {id:"SZ",text:"Swaziland"},
    {id:"SE",text:"Sweden"},
    {id:"CH",text:"Switzerland"},
    {id:"SY",text:"Syrian Arab Republic"},
    {id:"TW",text:"Taiwan, Province of China"},
    {id:"TJ",text:"Tajikistan"},
    {id:"TZ",text:"Tanzania, United Republic of"},
    {id:"TH",text:"Thailand"},
    {id:"TL",text:"Timor-Leste"},
    {id:"TG",text:"Togo"},
    {id:"TK",text:"Tokelau"},
    {id:"TO",text:"Tonga"},
    {id:"TT",text:"Trinidad and Tobago"},
    {id:"TN",text:"Tunisia"},
    {id:"TR",text:"Turkey"},
    {id:"TM",text:"Turkmenistan"},
    {id:"TC",text:"Turks and Caicos Islands"},
    {id:"TV",text:"Tuvalu"},
    {id:"UG",text:"Uganda"},
    {id:"UA",text:"Ukraine"},
    {id:"AE",text:"United Arab Emirates"},
    {id:"GB",text:"United Kingdom"},
    {id:"US",text:"United States"},
    {id:"UM",text:"United States Minor Outlying Islands"},
    {id:"UY",text:"Uruguay"},
    {id:"UZ",text:"Uzbekistan"},
    {id:"VU",text:"Vanuatu"},
    {id:"VE",text:"Venezuela, Bolivarian Republic of"},
    {id:"VN",text:"Viet Nam"},
    {id:"VG",text:"Virgin Islands, British"},
    {id:"VI",text:"Virgin Islands, U.S."},
    {id:"WF",text:"Wallis and Futuna"},
    {id:"EH",text:"Western Sahara"},
    {id:"YE",text:"Yemen"},
    {id:"ZM",text:"Zambia"},
    {id:"ZW",text:"Zimbabwe"}]);
